package HelloWorld;


/**
* HelloWorld/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* Friday, 1 February 2019 15:56:02 o'clock GMT
*/

public interface HelloOperations 
{

  //
  String hello_world ();
  String reverse (String str);
} // interface HelloOperations
